[package]
name = "csafe"
version = "0.3.11"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
structopt = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "safety"
harness = false
